'family':
    'fam1': 
        'father': ['/path/to/fam1.father.bam']
        'mother': ['/path/to/fam1.mother.bam']
        'child': ['/path/to/fam1.child1.bam', '/path/to/fam1.child2.bam']
    'family2': 
        'father': ['/path/to/fam2_dad.bam']
        'mother': ['/path/to/fam2_mother.bam']
        'child': ['/path/to/another/family2_kid.bam']
    'chimera_fam': 
        'father': ['/path/to/chimera_father.bam']
        'mother': ['/path/to/chimera_mother.bam']
        'child': ['/path/to/chimera/child.bam']
