# path to executables (default: Assumes that these are in the PATH)
SAMTOOLS: samtools
BGZIP: bgzip
TABIX: tabix
BCFTOOLS: bcftools
VT:  vt

# REFERENCE and DBSNP
GRCh38_REFERENCE: /home/users/cjyoon/Projects/mosaic/reference/Homo_sapiens_assembly38.fasta

GRCh37_REFERENCE: /home/users/cjyoon/reference/GRCh37/human_g1k_v37.fasta
